<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                     => __DIR__ . '/Module.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Log\SqlLogger'              => __DIR__ . '/src/Application/Log/SqlLogger.php',
);
