<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Users\Module'                            => __DIR__ . '/Module.php',
    'Users\Controller\UsersController'        => __DIR__ . '/src/Controller/UsersController.php',
    'Users\Controller\UsersControllerFactory' => __DIR__ . '/src/Controller/UsersControllerFactory.php',
    'Users\Entity\Confirmations'              => __DIR__ . '/src/Entity/Confirmations.php',
    'Users\Entity\ConfirmationsRepository'    => __DIR__ . '/src/Entity/ConfirmationsRepository.php',
    'Users\Entity\HierarchicalRole'           => __DIR__ . '/src/Entity/HierarchicalRole.php',
    'Users\Entity\Permission'                 => __DIR__ . '/src/Entity/Permission.php',
    'Users\Entity\User'                       => __DIR__ . '/src/Entity/User.php',
    'Users\Form\EditForm'                     => __DIR__ . '/src/Form/EditForm.php',
    'Users\Form\EditFormFactory'              => __DIR__ . '/src/Form/EditFormFactory.php',
    'Users\Form\Filter\EditFilter'            => __DIR__ . '/src/Form/Filter/EditFilter.php',
    'Users\Hydrator\UsersHydrator'            => __DIR__ . '/src/Hydrator/UsersHydrator.php',
    'Users\Hydrator\UsersHydratorFactory'     => __DIR__ . '/src/Hydrator/UsersHydratorFactory.php',
    'Users\Listener\UsersListener'            => __DIR__ . '/src/Listener/UsersListener.php',
    'Users\Listener\UsersListenerFactory'     => __DIR__ . '/src/Listener/UsersListenerFactory.php',
    'Users\Options\ModuleOptions'             => __DIR__ . '/src/Options/ModuleOptions.php',
    'Users\Service\UsersService'              => __DIR__ . '/src/Service/UsersService.php',
    'Users\Service\UsersServiceFactory'       => __DIR__ . '/src/Service/UsersServiceFactory.php',
    'Users\Validator\NoRecordExistsEdit'      => __DIR__ . '/src/Validator/NoRecordExistsEdit.php',
    'Users\View\Helper\EditForm'              => __DIR__ . '/src/View/Helper/EditForm.php',
);
