<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(

    'users/users/confirmation'      => __DIR__ . '/view/users/users/confirmation.phtml',
    'users/users/edit-form-success' => __DIR__ . '/view/users/users/edit-form-success.phtml',
    'users/users/edit-user'         => __DIR__ . '/view/users/users/edit-user.phtml',
    'users/users/index'             => __DIR__ . '/view/users/users/index.phtml',
    'users/users/_form'             => __DIR__ . '/view/users/users/_form.phtml',
);
