<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfcUserDoctrineORM\Module'                => __DIR__ . '/Module.php',
    'ZfcUserDoctrineORM\Entity\User'           => __DIR__ . '/src/ZfcUserDoctrineORM/Entity/User.php',
    'ZfcUserDoctrineORM\Mapper\User'           => __DIR__ . '/src/ZfcUserDoctrineORM/Mapper/User.php',
    'ZfcUserDoctrineORM\Options\ModuleOptions' => __DIR__ . '/src/ZfcUserDoctrineORM/Options/ModuleOptions.php',
);
