<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RememberMe\Module'                      => __DIR__ . '/Module.php',
    'RememberMe\Entity\RememberMe'           => __DIR__ . '/src/Entity/RememberMe.php',
    'RememberMe\Entity\RememberMeRepository' => __DIR__ . '/src/Entity/RememberMeRepository.php',
    'RememberMe\Mapper\RememberMe'           => __DIR__ . '/src/Mapper/RememberMe.php',
    'RememberMe\Options\ModuleOptions'       => __DIR__ . '/src/Options/ModuleOptions.php',
);
